language: cpp
compiler:
  - gcc
  - clang

before_install: 
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y  libsdl2-dev
  
install: sudo apt-get install libsdl2-dev
before_script: mv MakefileTravis Makefile && mkdir obj
script: make